
package wrt_catatan;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class Wrt extends javax.swing.JFrame {
    CRUD crud = new CRUD();
         
    String groupBy = "belum";
    String query ="";
    int cid;
    String stat;
    int sisa;
    
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");  
    java.util.Date date = new java.util.Date();  
    String dt =formatter.format(date); 
    
    private void displayData(){
        DefaultTableModel model = new DefaultTableModel(){
             @Override
            public boolean isCellEditable(int row, int column) {
       
            return false;
            }
        };

        model.addColumn("Nama");
        model.addColumn("Status");        
        
        BTN_hapus.setEnabled(false);
        try{
            if(groupBy.equalsIgnoreCase("belum")){
                this.query = "SELECT name, status FROM customer WHERE status = 'belum lunas' AND activity = 'aktif' ORDER BY name ASC";
            }else if(groupBy.equalsIgnoreCase("lunas")){
                this.query = "SELECT name, status FROM customer WHERE status = 'lunas' AND activity = 'aktif' ORDER BY name ASC";
            }else if(groupBy.equalsIgnoreCase("semua")){
                this.query = "SELECT name, status FROM customer WHERE activity = 'aktif' ORDER BY name ASC";
            }
            
            java.sql.Connection conn = (Connection)Confdb.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(this.query);

            while(res.next()){
                model.addRow(new Object[]{

                    res.getString(1),
                    res.getString(2)});
            }
            
            TABLE_debt.setModel(model);
            TABLE_debt.getTableHeader().setReorderingAllowed(false);
            TABLE_debt.getTableHeader().setResizingAllowed(false);
        }catch(SQLException e){
            System.out.println("Eror : " + e.getMessage());
        }
    }
    
    private void displayData(int id){
        DefaultTableModel model = new DefaultTableModel(){
             @Override
            public boolean isCellEditable(int row, int column) {
       
            return false;
            }
        };
        
        model.addColumn("Transaksi");  
        model.addColumn("Status");
        model.addColumn("Uang");          
    
        try{            

            this.query = "SELECT c_date,c_status,c_money FROM transaction WHERE id_customer ="+ id +" ORDER BY c_date ASC";
            
            java.sql.Connection conn = (Connection)Confdb.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(this.query);

            while(res.next()){
                model.addRow(new Object[]{

                    res.getString(1),
                    res.getString(2),
                    res.getString(3)});
            }
            
            TABLE_debt2.setModel(model);
            TABLE_debt2.getTableHeader().setReorderingAllowed(false);
            TABLE_debt2.getTableHeader().setResizingAllowed(false);
        }catch(SQLException e){
            System.out.println("Eror : " + e.getMessage());
        }
    }
     
    private void customerList(){
        try {
            query = "SELECT name FROM customer WHERE activity = 'aktif' ORDER BY name ASC ";
            java.sql.Connection conn = (Connection)Confdb.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(this.query);
            
            while(res.next()){
                String listKostumer = res.getString("name");
                CHOICE_customer.add(listKostumer);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Wrt.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public Wrt() {
        initComponents();
        displayData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        BTN_lunas = new javax.swing.JButton();
        BTN_belum = new javax.swing.JButton();
        BTN_semua = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLE_debt = new javax.swing.JTable();
        BTN_hutangBaru = new javax.swing.JButton();
        BTN_hapus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTN_addCustomer = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        FIELD_debt = new javax.swing.JTextField();
        BTN_back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        FIELD_catatan = new javax.swing.JTextField();
        BTN_save = new javax.swing.JButton();
        CHOICE_customer = new java.awt.Choice();
        jPanel5 = new javax.swing.JPanel();
        FIELD_customer = new javax.swing.JTextField();
        FIELD_phone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BTN_new = new javax.swing.JButton();
        BTN_back2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        LABEL_customer = new javax.swing.JLabel();
        LABEL_nohp = new javax.swing.JLabel();
        BTN_ubah = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLE_debt2 = new javax.swing.JTable();
        BTN_bayar = new javax.swing.JButton();
        BTN_back3 = new javax.swing.JButton();
        BTN_hutangbaru2 = new javax.swing.JButton();
        LABEL_sisa = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        FIELD_customer2 = new javax.swing.JTextField();
        FIELD_phone2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BTN_back4 = new javax.swing.JButton();
        BTN_update = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        FIELD_bayar = new javax.swing.JTextField();
        LABEL_customer2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BTN_bayar2 = new javax.swing.JButton();
        BTN_back5 = new javax.swing.JButton();
        LABEL_sisa2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 255, 0));

        BTN_lunas.setBackground(new java.awt.Color(255, 255, 0));
        BTN_lunas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTN_lunas.setText("SUDAH LUNAS");
        BTN_lunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_lunasActionPerformed(evt);
            }
        });

        BTN_belum.setBackground(new java.awt.Color(255, 255, 0));
        BTN_belum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTN_belum.setText("BELUM LUNAS");
        BTN_belum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_belumActionPerformed(evt);
            }
        });

        BTN_semua.setBackground(new java.awt.Color(255, 255, 0));
        BTN_semua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTN_semua.setText("SEMUA");
        BTN_semua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_semuaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Rockwell Condensed", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("CATATAN UTANG");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BTN_lunas, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(BTN_belum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(BTN_semua)
                .addGap(27, 27, 27))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_lunas)
                    .addComponent(BTN_belum)
                    .addComponent(BTN_semua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 120));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        TABLE_debt.setBackground(new java.awt.Color(255, 255, 0));
        TABLE_debt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TABLE_debt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLE_debtMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABLE_debt);

        BTN_hutangBaru.setBackground(new java.awt.Color(204, 204, 204));
        BTN_hutangBaru.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BTN_hutangBaru.setText("CATAT UTANG BARU");
        BTN_hutangBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_hutangBaruActionPerformed(evt);
            }
        });

        BTN_hapus.setBackground(new java.awt.Color(204, 204, 204));
        BTN_hapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BTN_hapus.setText("HAPUS KOSTUMER");
        BTN_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(BTN_hutangBaru)
                        .addGap(35, 35, 35)
                        .addComponent(BTN_hapus)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTN_hutangBaru, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(BTN_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Siapa yang ngutang");

        BTN_addCustomer.setBackground(new java.awt.Color(204, 204, 204));
        BTN_addCustomer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTN_addCustomer.setText("BARU");
        BTN_addCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_addCustomerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Berapa Utangnya?");

        FIELD_debt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FIELD_debtKeyTyped(evt);
            }
        });

        BTN_back.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTN_back.setText("KEMBALI");
        BTN_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_backActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("CATAT UTANG BARU");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("catatan (opsional)");

        FIELD_catatan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FIELD_catatanKeyTyped(evt);
            }
        });

        BTN_save.setBackground(new java.awt.Color(204, 204, 204));
        BTN_save.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTN_save.setText("SIMPAN");
        BTN_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTN_save, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FIELD_catatan, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FIELD_debt, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_back)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(CHOICE_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(BTN_addCustomer)))
                        .addContainerGap(120, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTN_back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CHOICE_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_addCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FIELD_debt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FIELD_catatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTN_save, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        FIELD_customer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        FIELD_customer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FIELD_customerKeyTyped(evt);
            }
        });

        FIELD_phone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        FIELD_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FIELD_phoneKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Nama");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("No HP (opsional)");

        BTN_new.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTN_new.setText("SIMPAN");
        BTN_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_newActionPerformed(evt);
            }
        });

        BTN_back2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTN_back2.setText("KEMBALI");
        BTN_back2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_back2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_back2)
                    .addComponent(BTN_new, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FIELD_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FIELD_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(BTN_back2)
                .addGap(66, 66, 66)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FIELD_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FIELD_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTN_new, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        LABEL_customer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LABEL_customer.setText("jLabel7");

        LABEL_nohp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LABEL_nohp.setText("jLabel8");

        BTN_ubah.setText("UBAH DATA");
        BTN_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ubahActionPerformed(evt);
            }
        });

        TABLE_debt2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TABLE_debt2);

        BTN_bayar.setText("BAYAR");
        BTN_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_bayarActionPerformed(evt);
            }
        });

        BTN_back3.setText("KEMBALI");
        BTN_back3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_back3ActionPerformed(evt);
            }
        });

        BTN_hutangbaru2.setText("UTANG BARU");
        BTN_hutangbaru2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_hutangbaru2ActionPerformed(evt);
            }
        });

        LABEL_sisa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LABEL_sisa.setText("jLabel9");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Sisa:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Rp.");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(BTN_back3)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(LABEL_nohp, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(LABEL_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(162, 162, 162))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(LABEL_sisa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(BTN_ubah))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(BTN_hutangbaru2)
                                    .addGap(18, 18, 18)
                                    .addComponent(BTN_bayar))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(BTN_back3)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LABEL_sisa)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LABEL_nohp))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(LABEL_customer))
                        .addGap(57, 57, 57)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_hutangbaru2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        FIELD_customer2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        FIELD_customer2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FIELD_customer2KeyTyped(evt);
            }
        });

        FIELD_phone2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        FIELD_phone2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FIELD_phone2KeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Nama");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("No HP (opsional)");

        BTN_back4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTN_back4.setText("KEMBALI");
        BTN_back4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_back4ActionPerformed(evt);
            }
        });

        BTN_update.setText("SIMPAN");
        BTN_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_back4)
                    .addComponent(FIELD_phone2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(FIELD_customer2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(BTN_update, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(BTN_back4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FIELD_customer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FIELD_phone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTN_update, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        FIELD_bayar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        FIELD_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FIELD_bayarKeyTyped(evt);
            }
        });

        LABEL_customer2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LABEL_customer2.setText("jLabel9");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Jumlah Pelunasan");

        BTN_bayar2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTN_bayar2.setText("BAYAR");
        BTN_bayar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_bayar2ActionPerformed(evt);
            }
        });

        BTN_back5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTN_back5.setText("KEMBALI");
        BTN_back5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_back5ActionPerformed(evt);
            }
        });

        LABEL_sisa2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LABEL_sisa2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LABEL_sisa2.setText("jLabel12");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Rp.");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_back5)
                    .addComponent(BTN_bayar2)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(FIELD_bayar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LABEL_sisa2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LABEL_customer2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(BTN_back5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABEL_customer2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LABEL_sisa2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FIELD_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(BTN_bayar2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab6", jPanel8);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 450, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(461, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_hutangBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_hutangBaruActionPerformed
        jTabbedPane1.setSelectedIndex(1);
        BTN_lunas.setVisible(false);
        BTN_belum.setVisible(false);
        BTN_semua.setVisible(false);
        customerList();
    }//GEN-LAST:event_BTN_hutangBaruActionPerformed

    private void BTN_lunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_lunasActionPerformed
        groupBy = "lunas";
        displayData();
    }//GEN-LAST:event_BTN_lunasActionPerformed

    private void BTN_belumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_belumActionPerformed
        groupBy = "belum";
        displayData();
    }//GEN-LAST:event_BTN_belumActionPerformed

    private void BTN_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_backActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        BTN_lunas.setVisible(true);
        BTN_belum.setVisible(true);       
        BTN_semua.setVisible(true);
        displayData();

    }//GEN-LAST:event_BTN_backActionPerformed

    private void BTN_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_saveActionPerformed
        String cid_CHOICE = CHOICE_customer.getSelectedItem();        
        
        if(FIELD_debt.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Tolong isi utangnya");
        }else if(FIELD_debt.getText().substring(0, 1).equals("0")){
            JOptionPane.showMessageDialog(null,"Tolong isi yang benar");
            FIELD_debt.setText(null);
        }
        else{
            int confirm = JOptionPane.showConfirmDialog(this,"Yakin ingin catat?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            Integer duitINT = Integer.valueOf(FIELD_debt.getText());
            if (confirm == JOptionPane.YES_OPTION){
                cid = crud.find_cid(cid_CHOICE);
                if(FIELD_catatan.getText().equals("")){
                    crud.add_transaction(cid, duitINT, dt);
                }else{
                    crud.add_transaction(cid, duitINT, FIELD_catatan.getText(), dt);    
                }
                JOptionPane.showMessageDialog(null,"Sukses");
                stat="belum lunas";
                crud.modify_stat(cid,stat);
            }else if(confirm == JOptionPane.NO_OPTION){
                FIELD_debt.setText(null);
                FIELD_catatan.setText(null);
            }
            
        }

    }//GEN-LAST:event_BTN_saveActionPerformed

    private void FIELD_debtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FIELD_debtKeyTyped
        char c = evt.getKeyChar();      
        if (!Character.isDigit(c)){
            evt.consume();
            
        }
    }//GEN-LAST:event_FIELD_debtKeyTyped

    private void FIELD_catatanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FIELD_catatanKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isLetter(c)&& !Character.isWhitespace(c) && !Character.isISOControl(c)&& !Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_FIELD_catatanKeyTyped

    private void BTN_semuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_semuaActionPerformed
        groupBy = "semua";
        displayData();
    }//GEN-LAST:event_BTN_semuaActionPerformed

    private void BTN_addCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_addCustomerActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_BTN_addCustomerActionPerformed

    private void BTN_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_newActionPerformed
        if(FIELD_customer.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Tolong isi nama");
        }else{
            if(FIELD_phone.getText().equals("")){
                crud.add_customer(FIELD_customer.getText());
                JOptionPane.showMessageDialog(null,"Sukses");
            }else if(FIELD_phone.getText().length() < 10 ){
                JOptionPane.showMessageDialog(null,"no hp terlalu pendek");
            }else if(FIELD_phone.getText().length() > 15 ){
                JOptionPane.showMessageDialog(null,"no hp terlalu panjang");
            }else{
                crud.add_customer(FIELD_customer.getText(),FIELD_phone.getText());
                JOptionPane.showMessageDialog(null,"Sukses");
            }
                    
            
        }
       
    }//GEN-LAST:event_BTN_newActionPerformed

    private void FIELD_phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FIELD_phoneKeyTyped
        char c = evt.getKeyChar();      
        if (!Character.isDigit(c)){
            evt.consume();
            
        }
        
    }//GEN-LAST:event_FIELD_phoneKeyTyped

    private void FIELD_customerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FIELD_customerKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isLetter(c)&& !Character.isWhitespace(c)){
            evt.consume();
        }
        
    }//GEN-LAST:event_FIELD_customerKeyTyped

    private void BTN_back2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_back2ActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_BTN_back2ActionPerformed

    private void TABLE_debtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLE_debtMouseClicked
        int baris = TABLE_debt.rowAtPoint(evt.getPoint());
        stat = TABLE_debt.getValueAt(baris, 1).toString();
        cid = crud.find_cid(TABLE_debt.getValueAt(baris, 0).toString());
        if(evt.getClickCount() == 1){
            if(stat.equals("lunas")){
                BTN_hapus.setEnabled(true);                        
            }else{
                BTN_hapus.setEnabled(false); 
            }
        }
        else if(evt.getClickCount() == 2){
            jTabbedPane1.setSelectedIndex(3);
            BTN_lunas.setVisible(false);
            BTN_belum.setVisible(false);
            BTN_semua.setVisible(false);
            
            
            
            
            sisa = crud.sisa(cid);
            
            displayData(cid);
            String hp = crud.find_phone(cid);
            String sisaSTR = String.valueOf(sisa);
            LABEL_customer.setText(TABLE_debt.getValueAt(baris, 0).toString());
            LABEL_nohp.setText(hp);
            LABEL_sisa.setText(sisaSTR);
            
            if(stat.equals("lunas")){
                BTN_bayar.setEnabled(false);
            }else{
                BTN_bayar.setEnabled(true);
            }
            
        }
    }//GEN-LAST:event_TABLE_debtMouseClicked

    private void BTN_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_bayarActionPerformed
        jTabbedPane1.setSelectedIndex(5);
        LABEL_customer2.setText(LABEL_customer.getText());
        LABEL_sisa2.setText(LABEL_sisa.getText());
    }//GEN-LAST:event_BTN_bayarActionPerformed

    private void BTN_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ubahActionPerformed
        jTabbedPane1.setSelectedIndex(4);
        FIELD_customer2.setText(LABEL_customer.getText());
        
        if(LABEL_nohp.getText().equals("-")){
            FIELD_phone2.setText(null);
        }else{
            FIELD_phone2.setText(LABEL_nohp.getText());
        }
    }//GEN-LAST:event_BTN_ubahActionPerformed

    private void BTN_back3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_back3ActionPerformed
        jTabbedPane1.setSelectedIndex(0);
        BTN_lunas.setVisible(true);
        BTN_belum.setVisible(true);       
        BTN_semua.setVisible(true);
        displayData();

    }//GEN-LAST:event_BTN_back3ActionPerformed

    private void BTN_hutangbaru2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_hutangbaru2ActionPerformed
        jTabbedPane1.setSelectedIndex(1);        
        customerList();
    }//GEN-LAST:event_BTN_hutangbaru2ActionPerformed

    private void BTN_back4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_back4ActionPerformed
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_BTN_back4ActionPerformed

    private void BTN_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_updateActionPerformed
        if(FIELD_customer2.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Tolong isi nama");
        }else{
            if(FIELD_phone2.getText().equals("")){
                crud.modify_customer(cid,FIELD_customer2.getText());
                LABEL_customer.setText(FIELD_customer2.getText());
                JOptionPane.showMessageDialog(null,"Sukses");
            }else if(FIELD_phone2.getText().length() < 10 ){
                JOptionPane.showMessageDialog(null,"no hp terlalu pendek");
            }else if(FIELD_phone2.getText().length() > 15 ){
                JOptionPane.showMessageDialog(null,"no hp terlalu panjang");
            }else{
                crud.modify_customer(cid,FIELD_customer2.getText(),FIELD_phone2.getText());
                JOptionPane.showMessageDialog(null,"Sukses");
                LABEL_customer.setText(FIELD_customer2.getText());
                LABEL_nohp.setText(FIELD_phone2.getText());
            }
            

            
        }

    }//GEN-LAST:event_BTN_updateActionPerformed

    private void FIELD_customer2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FIELD_customer2KeyTyped
        char c = evt.getKeyChar();
        if(!Character.isLetter(c)&& !Character.isWhitespace(c)){
            evt.consume();
        }

    }//GEN-LAST:event_FIELD_customer2KeyTyped

    private void FIELD_phone2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FIELD_phone2KeyTyped
        char c = evt.getKeyChar();      
        if (!Character.isDigit(c)){
            evt.consume();            
        }

    }//GEN-LAST:event_FIELD_phone2KeyTyped

    private void FIELD_bayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FIELD_bayarKeyTyped
        char c = evt.getKeyChar();      
        if (!Character.isDigit(c)){
            evt.consume();            
        }
        
    }//GEN-LAST:event_FIELD_bayarKeyTyped

    private void BTN_bayar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_bayar2ActionPerformed
        if(FIELD_bayar.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Tolong isi utangnya");
        }else if(FIELD_bayar.getText().substring(0, 1).equals("0")){
            JOptionPane.showMessageDialog(null,"Tolong isi yang benar");
            FIELD_bayar.setText(null);
        }else{
            int confirm = JOptionPane.showConfirmDialog(this,"Yakin ingin catat?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            Integer bayarINT = Integer.valueOf(FIELD_bayar.getText());
            if (confirm == JOptionPane.YES_OPTION){
                if(bayarINT > sisa){
                    bayarINT = sisa;
                    LABEL_sisa2.setText("0");
                }

                cid = crud.find_cid(LABEL_customer2.getText());
                crud.add_transaction(cid, "pelunasan", bayarINT,dt);   
                sisa = crud.sisa(cid);                          
                String sisaSTR = String.valueOf(sisa);
                JOptionPane.showMessageDialog(null,"Sukses");
                LABEL_sisa2.setText(sisaSTR);
                
            }else if(confirm == JOptionPane.NO_OPTION){
                FIELD_bayar.setText(null);                
            }
           
        }
        
    }//GEN-LAST:event_BTN_bayar2ActionPerformed

    private void BTN_back5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_back5ActionPerformed
        displayData(cid);
        String sisaSTR = String.valueOf(sisa);     
        LABEL_sisa.setText(sisaSTR);
        if(sisa == 0){
            stat="lunas";
        }
        
        crud.modify_stat(cid,stat);
        
        if(stat.equals("lunas")){
            BTN_bayar.setEnabled(false);
        }else{
            BTN_bayar.setEnabled(true);
        }

        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_BTN_back5ActionPerformed

    private void BTN_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_hapusActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,"Yakin ingin hapus?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION){
            crud.modify_activity(cid);
            JOptionPane.showMessageDialog(null,"Sukses");
        }else if(confirm == JOptionPane.NO_OPTION){
            
        }

    }//GEN-LAST:event_BTN_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Wrt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Wrt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Wrt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Wrt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wrt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_addCustomer;
    private javax.swing.JButton BTN_back;
    private javax.swing.JButton BTN_back2;
    private javax.swing.JButton BTN_back3;
    private javax.swing.JButton BTN_back4;
    private javax.swing.JButton BTN_back5;
    private javax.swing.JButton BTN_bayar;
    private javax.swing.JButton BTN_bayar2;
    private javax.swing.JButton BTN_belum;
    private javax.swing.JButton BTN_hapus;
    private javax.swing.JButton BTN_hutangBaru;
    private javax.swing.JButton BTN_hutangbaru2;
    private javax.swing.JButton BTN_lunas;
    private javax.swing.JButton BTN_new;
    private javax.swing.JButton BTN_save;
    private javax.swing.JButton BTN_semua;
    private javax.swing.JButton BTN_ubah;
    private javax.swing.JButton BTN_update;
    private java.awt.Choice CHOICE_customer;
    private javax.swing.JTextField FIELD_bayar;
    private javax.swing.JTextField FIELD_catatan;
    private javax.swing.JTextField FIELD_customer;
    private javax.swing.JTextField FIELD_customer2;
    private javax.swing.JTextField FIELD_debt;
    private javax.swing.JTextField FIELD_phone;
    private javax.swing.JTextField FIELD_phone2;
    private javax.swing.JLabel LABEL_customer;
    private javax.swing.JLabel LABEL_customer2;
    private javax.swing.JLabel LABEL_nohp;
    private javax.swing.JLabel LABEL_sisa;
    private javax.swing.JLabel LABEL_sisa2;
    private javax.swing.JTable TABLE_debt;
    private javax.swing.JTable TABLE_debt2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
